export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUTREQUEST: "LOGOUT_REQUEST",
    LOGOUTSUCCESS: "LOGOUT_SUCCESS",
    LOGOUTFAILURE: "LOGOUT_FAILURE",
}